force-app/main/default/objects/API__c/API__c.object-meta.xml
<CustomObject>
    <label>API</label>
    <nameField>
        <label>API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parameter__c/Parameter__c.object-meta.xml
<CustomObject>
    <label>Parameter</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Parameter__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <referenceTo>API__c</referenceTo>
    <relationshipName>API_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Parameter__c/fields/Key_Custom__c.field-meta.xml
<CustomField>
    <fullName>Key_Custom__c</fullName>
    <label>Key Custom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parameter__c/fields/Use__c.field-meta.xml
<CustomField>
    <fullName>Use__c</fullName>
    <label>Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Body</fullName>
            </value>
            <value>
                <fullName>Endpoint</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parameter__c/fields/Value_Custom__c.field-meta.xml
<CustomField>
    <fullName>Value_Custom__c</fullName>
    <label>Value Custom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CalloutConfigServiceTest.cls
@isTest
private class CalloutConfigServiceTest {
	@TestSetup
	static void makeData() {
		API__c api = new API__c(
			Name = 'Geocoding API',
			Method__c = 'GET',
			Endpoint__c = 'https://geocode.maps.co/search'
		);
		insert api;
		insert new Parameter__c(
			API__c = api.Id,
			Use__c = 'Endpoint',
			Key_Custom__c = 'testkey',
			Value_Custom__c = 'testvalue'
		);
	}

	@IsTest
	static void testEndpoint() {
		Test.startTest();
		IAPICalls geoCode = APICalls.newInstance()
			.setApiName('Geocoding API')
			.setEndpointParameter('q', 'illinois')
			.prepare();
		Test.stopTest();
		System.assert(
			geoCode.getRequest()
				.getEndpoint()
				.startsWith('https://geocode.maps.co/search'),
			'Did not start with expected endpoint'
		);
		System.assert(
			geoCode.getRequest().getEndpoint().contains('q=illinois'),
			'Did not add dynamic endpoint parameter'
		);
		System.assert(
			geoCode.getRequest().getEndpoint().contains('testkey=testvalue'),
			'Did not add parameter record endpoint parameter'
		);
	}

	@IsTest
	static void testCall() {
		Test.setMock(HttpCalloutMock.class, new APICallsTestMocker());
		Test.startTest();
		IAPICalls geoCode = APICalls.newInstance()
			.setApiName('Geocoding API')
			.setEndpointParameter('q', 'illinois')
			.prepare()
			.send();
		Test.stopTest();
		System.assertEquals(
			geoCode.getResponse().getStatusCode(),
			200,
			'Did not receive expected status code'
		);
	}
}