force-app/main/default/objects/API__c/API__c.object-meta.xml
<CustomObject>
    <label>API</label>
    <nameField>
        <label>API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parameter__c/Parameter__c.object-meta.xml
<CustomObject>
    <label>Parameter</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Parameter__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <referenceTo>API__c</referenceTo>
    <relationshipName>API_Headers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Parameter__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Authorization</fullName>
            </value>
            <value>
                <fullName>Content-Type</fullName>
            </value>
            <value>
                <fullName>User-Agent</fullName>
            </value>
            <value>
                <fullName>Accept-Encoding</fullName>
            </value>
            <value>
                <fullName>Accept-Language</fullName>
            </value>
            <value>
                <fullName>Cache-Control</fullName>
            </value>
            <value>
                <fullName>If-Modified-Since</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parameter__c/fields/Key_Custom__c.field-meta.xml
<CustomField>
    <fullName>Key_Custom__c</fullName>
    <label>Key Custom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parameter__c/fields/Use__c.field-meta.xml
<CustomField>
    <fullName>Use__c</fullName>
    <label>Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Body</fullName>
            </value>
            <value>
                <fullName>Endpoint</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parameter__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>application/json;charset=UTF-8</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
            <value>
                <fullName>no-cache</fullName>
            </value>
            <value>
                <fullName>no-store</fullName>
            </value>
            <value>
                <fullName>gzip</fullName>
            </value>
            <value>
                <fullName>deflate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parameter__c/fields/Value_Custom__c.field-meta.xml
<CustomField>
    <fullName>Value_Custom__c</fullName>
    <label>Value Custom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parameter__c/fields/Value_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Value_Encrypted__c</fullName>
    <label>Value Encrypted</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/CalloutConfigService.cls
public with sharing class CalloutConfigService implements ICalloutConfigService {
	Id apiId;
	String apiName;
	ICalloutService service;
	Map<String, String> endPointParameters;
	Map<String, String> headerParameters;
	Map<String, String> jsonBodyParameters;
	String bodyString;

	public static ICalloutConfigService newInstance() {
		return (ICalloutConfigService) new CalloutConfigService();
	}

	public static ICalloutConfigService newInstance(String apiName) {
		return (ICalloutConfigService) new CalloutConfigService()
			.setApiName(apiName);
	}

	public ICalloutConfigService setApiId(Id apiId) {
		this.apiId = apiId;
		initialize();
		return this;
	}

	public ICalloutConfigService setApiName(String apiName) {
		this.apiName = apiName;
		initialize();
		return this;
	}

	void initialize() {
		this.endPointParameters = new Map<String, String>();
		this.headerParameters = new Map<String, String>();
		this.jsonBodyParameters = new Map<String, String>();
	}

	public ICalloutConfigService setEndpointParameter(
		String key,
		String value
	) {
		this.endPointParameters.put(key, value);
		return this;
	}

	public ICalloutConfigService setHeaderParameter(String key, String value) {
		this.headerParameters.put(key, value);
		return this;
	}

	public ICalloutConfigService setAuthorization(String value) {
		this.headerParameters.put('Authorization', value);
		return this;
	}

	public ICalloutConfigService setJsonBodyParameter(
		String key,
		String value
	) {
		this.jsonBodyParameters.put(key, value);
		return this;
	}

	public ICalloutConfigService setStringBody(String value) {
		this.bodyString = value;
		return this;
	}

	public ICalloutService makeCall() {
		getCalloutService();
		return this.service.send();
	}

	public ICalloutService getCalloutService() {
		API__c api = getAPI();
		this.service = CalloutService.newInstance()
			.setEndPoint(api.Endpoint__c)
			.setMethod(api.Method__c);
		prepareParameters(api);
		addEndpointParameters();
		addHeaderParameers();
		addBodyParameters();
		return this.service;
	}

	@TestVisible
	void prepareParameters(API__c api) {
		for (Parameter__c p : [
			SELECT
				Id,
				Use__c,
				Value_Encrypted__c,
				Key__c,
				Key_Custom__c,
				Value__c,
				Value_Custom__c
			FROM Parameter__c
			WHERE API__c = :api.Id
			WITH SECURITY_ENFORCED
		]) {
			switch on p.Use__c {
				when 'Endpoint' {
					this.endPointParameters.put(
						p.Key__c ?? p.Key_Custom__c,
						p.Value__c ?? p.Value_Encrypted__c ?? p.Value_Custom__c
					);
				}
				when 'Header' {
					this.headerParameters.put(
						p.Key__c ?? p.Key_Custom__c,
						p.Value__c ?? p.Value_Encrypted__c ?? p.Value_Custom__c
					);
				}
				when 'Body' {
					if (api.Body_Type__c == 'String') {
						this.bodyString = p.Value__c ?? p.Value_Encrypted__c ??
							p.Value_Custom__c;
					} else {
						this.jsonBodyParameters.put(
							p.Key__c ?? p.Key_Custom__c,
							p.Value__c ?? p.Value_Encrypted__c ??
								p.Value_Custom__c
						);
					}
				}
				when else {
					Logger.info(
						'Invalid Parameter Type with record Id : ' + p.Id
					);
				}
			}
		}
	}

	void addEndpointParameters() {
		if (this.endPointParameters.isEmpty())
			return;

		String endpoint = this.service.getRequest().getEndpoint();

		if (!endpoint.contains('?')) {
			endpoint += '?';
		}

		for (String s : this.endPointParameters.keySet()) {
			String operator = endpoint.endsWith('?') ? '' : '&';
			endpoint += operator + s + '=' + this.endPointParameters.get(s);
		}

		this.service.setEndPoint(endPoint);
	}

	void addHeaderParameers() {
		if (this.headerParameters.isEmpty())
			return;

		for (String s : this.headerParameters.keySet()) {
			this.service.setHeader(s, this.headerParameters.get(s));
		}
	}

	void addBodyParameters() {
		if (String.isNotBlank(this.bodyString)) {
			this.service.setBody(this.bodyString);
		} else if (!this.jsonBodyParameters.isEmpty()) {
			this.service.setBody(JSON.serialize(this.jsonBodyParameters));
		}
	}

	API__c getAPI() {
		return [
			SELECT Id, Name, Endpoint__c, Method__c, Body_Type__c
			FROM API__c
			WHERE Id = :apiId OR Name = :apiName
		];
	}
}